/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BillingDetailsDTO { 
    name?: string;
    email?: string;
    phone: string;
    country?: string;
    city: string;
    street: string;
    buildingNumber: number;
}

export interface CheckoutResponseDTO {
  success: boolean;
  message: string;
}