/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CartItemDetailsDTO { 
    userId?: number;
    productId?: number;
    quantity: number;
    name: string;
    description?: string;
    totalPricePerProduct?: number;
    image_url?: string;
    available_quantity?: number;
    unit_price: number;
}

