/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderItemDTO { 
    userId?: number;
    userName?: string;
    orderId?: number;
    productId?: number;
    productName?: string;
    price?: number;
    quantity?: number;
}

