/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderDTO { 
    id?: number;
    userId?: number;
    totalCost?: number;
    paymentMethod?: OrderDTO.PaymentMethodEnum;
    orderedAt?: string;
    status?: OrderDTO.StatusEnum;
}
export namespace OrderDTO {
    export const PaymentMethodEnum = {
        CreditCard: 'CREDIT_CARD',
        Paypal: 'PAYPAL',
        Cash: 'CASH'
    } as const;
    export type PaymentMethodEnum = typeof PaymentMethodEnum[keyof typeof PaymentMethodEnum];
    export const StatusEnum = {
        Pending: 'PENDING',
        Shipped: 'SHIPPED',
        Delivered: 'DELIVERED',
        Cancelled: 'CANCELLED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


