/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDTO { 
    id?: number;
    name?: string;
    username?: string;
    phoneNumber?: string;
    email?: string;
    password?: string;
    creditLimit?: number;
    birthDate?: string;
    job?: string;
    createdAt?: string;
    role?: string;
}

